### ISSUE TITLE
require() of ES modules is not supported

### ISSUE THREAD

**Issue by anupammajhi** [inikulin/parse5#663]
parse5 is being used by puppeteer and I get this error in the latest version(7.1.0) of parse5 (via puppeteer)

```
internal/modules/cjs/loader.js:1253
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /data/agents/agent31/_work/10/s/.npm-global/lib/node_modules/aws-azure-login/node_modules/parse5/dist/cjs/index.js
require() of ES modules is not supported.
require() of /data/agents/agent31/_work/10/s/.npm-global/lib/node_modules/aws-azure-login/node_modules/parse5/dist/cjs/index.js from /data/agents/agent31/_work/10/s/.npm-global/lib/node_modules/aws-azure-login/node_modules/cheerio/lib/parsers/parse5-adapter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /data/agents/agent31/_work/10/s/.npm-global/lib/node_modules/aws-azure-login/node_modules/parse5/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1253:13)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/data/agents/agent31/_work/10/s/.npm-global/lib/node_modules/aws-azure-login/node_modules/cheerio/lib/parsers/parse5-adapter.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/data/agents/agent31/_work/10/s/.npm-global/lib/node_modules/aws-azure-login/node_modules/cheerio/lib/index.js:41:27)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by maoxiaoke** [comment]
me too

**Comment by alizeegtd** [comment]
same here

**Comment by jonesnc** [comment]
I'm also getting this error when using the `mjml` npm package, which uses `parse5` as a dependency.

**Comment by 43081j** [comment]
@fb55 is this because cheerio ships esm _and_ cjs but parse5 is esm-only? so cjs consumers of cheerio will get a runtime error?

i was also going to say im surprised people are running into this without updating but it seems cheerio is on 7.x.

**Comment by fb55** [comment]
Cheerio is a dual module, so is parse5. That's why everything works well together. CJS users of cheerio will not even notice that ESM is available.

**Comment by simon-abbott** [comment]
Same issue here, this is blocking production deploys for our app. Something definitely changed between v7.0.0 and v7.1.0 that is making node think the files in `dist/cjs` are actually ESM files.

**Comment by fb55** [comment]
Looks like the `package.json` file is no longer added. Patch should be there soon.

**Comment by fb55** [comment]
Fix incoming with #664

**Comment by maoxiaoke** [comment]
@jonesnc How about publishing a major version to support esm only, like [globby](https://github.com/sindresorhus/globby).

**Comment by jonesnc** [comment]
@maoxiaoke I'm not involved with the `mjml` project, but that sounds like a good idea to me.

**Comment by fb55** [comment]
`7.1.1` has been published.

**Comment by jonesnc** [comment]
I can see [version `7.1.1` on npm](https://www.npmjs.com/package/parse5/v/7.1.1).

**Comment by ludwhe** [comment]
Is there a plan to include this change for `parse5-html-rewriting-stream` as well? I am writing a VS Code extension which depends on it and loading fails as VS Code extensions target CommonJS.

**Comment by wooorm** [comment]
This issue is unrelated to your question.

The package you mention is ESM only. VSCode does not support ESM well currently.
When you make VSCode extensions, you can bundle your things anyway: write ESM, and use esbuild or so to create a bundle.
