### ISSUE TITLE
TypeError: this.html.charCodeAt is not a function

### ISSUE THREAD

**Issue by faustman** [inikulin/parse5#68]
## Error
```
/app/node_modules/parse5/lib/tokenization/preprocessor.js:32
    this.pos = this.html.charCodeAt(0) === $.BOM ? 0 : -1;
                         ^

TypeError: this.html.charCodeAt is not a function
    at new module.exports (/app/node_modules/parse5/lib/tokenization/preprocessor.js:32:26)
    at new module.exports (/app/node_modules/parse5/lib/tokenization/tokenizer.js:148:25)
    at Parser._reset (/app/node_modules/parse5/lib/tree_construction/parser.js:399:22)
    at Parser.parse (/app/node_modules/parse5/lib/tree_construction/parser.js:361:10)
    at readHtmlFile (/app/index.js:35:17)
    at /app/index.js:23:22
    at Array.forEach (native)
    at /app/index.js:20:11
    at FSReqWrap.oncomplete (fs.js:82:15)
```

## Env:
* OS: OS X 10.10.4
* NodeJS: v4.0.0
* npm: v2.14.2

**Comment by inikulin** [comment]
Can you provide code which causes this error, please?

**Comment by inikulin** [comment]
Seems like `html` argument of the `parse` function is not a string. This is the cause of error.

**Comment by faustman** [comment]
Hi,
here this:

index.js:
```
var Parser = require('parse5').Parser;
var fs = require('fs');

var parser = new Parser();

var html = fs.readFileSync('./test.html');
var doc = parser.parse(html);

console.log(doc);

```

test.html:
```
<html>
  <title>HEY!</title>
</html>

```

I think the `html` is a `Buffer`.. there is problem?

**Comment by faustman** [comment]
Oh, sorry..
My bad,

should be
```
var html = fs.readFileSync('./test.html', { encoding: 'utf8' });
```
