### ISSUE TITLE
Package subpath './lib/parser/index.js' is not defined by "exports"

### ISSUE THREAD

**Issue by testtestingtester** [inikulin/parse5#861]
Error - Package subpath './lib/parser/index.js' is not defined by "exports" in /var/task/.netlify/functions-internal/server/node_modules/parse5/package.json imported from /var/task/.netlify/functions-internal/server/node_modules/hast-util-raw/lib/index.js

**Comment by fb55** [comment]
It seems like you have a version mismatch. I'd be surprised if there is a release of `hast-util-raw` that specifies parse5@7 as a dependency AND pulls in this path. Try removing your package-lock.json and node_modules, then installing things again.

**Comment by wooorm** [comment]
Yep, likely bundler problem. Or someone overwrote this.
Shouldn't be a problem normally

**Comment by revelt** [comment]
I'm having the same problem, one of my packages is breaking because `esbuild` can't resolve the `entities/lib/decode.js` of the `parse5` (v6 instead of v7) which comes from `hast-util-raw`.

My setup is a monorepo. I discovered that actually I've got two `parse5` — `parse5` v6 hoisted to the root `node_modules` and `parse5` v7.1.2 within the package local `node_modules`.

`npm ls parse5` yields:

<img width="1295" alt="Screenshot 2023-03-28 at 19 56 57" src="https://user-images.githubusercontent.com/8344688/228340732-6214a8c6-4082-45ac-bc7a-9cb70ccb9403.png">

which means, somehow v7 is defining the paths but they're being referenced from hoisted `node_modules` instead of local `node_modules`.

To solve this conundrum, rehype maintainers (let me kindly CC @wooorm) should take two actions:

1. bump `rehype-parse@8.0.4` dependencies to consume `parse5@7.x`
2. bump `hast-util-to-html@8.0.4` to bump `hast-util-raw` dependency to v.8

Whoever wants to recreate the issue, here's the recipe:

1. `git clone git@github.com:codsen/codsen.git`
2. `npm i && npm run build`

The build should fail `remark-conventional-commit-changelog-timeline` with something along the lines:

```bash
> remark-conventional-commit-changelog-timeline@3.0.7 pretest
> npm run lect && npm run build


> remark-conventional-commit-changelog-timeline@3.0.7 lect
> node '../../ops/lect/lect.js' && npm run prettier -- 'README.md' '.all-contributorsrc' --write --loglevel 'silent'


> remark-conventional-commit-changelog-timeline@3.0.7 prettier
> prettier "README.md" ".all-contributorsrc" "--write" "--loglevel" "silent"


> remark-conventional-commit-changelog-timeline@3.0.7 build
> node '../../ops/scripts/esbuild.js' && node '../../ops/scripts/fix-cjs.js' && npm run dts

✘ [ERROR] Could not resolve "entities/lib/escape.js"

    node_modules/parse5/dist/serializer/index.js:2:44:
      2 │ import { escapeText, escapeAttribute } from 'entities/lib/escape.js';
        ╵                                             ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "entities/lib/escape.js" as external to exclude it from the bundle, which
  will remove this error.

✘ [ERROR] Could not resolve "entities/lib/decode.js"

    node_modules/parse5/dist/tokenizer/index.js:4:62:
      4 │ import { htmlDecodeTree, BinTrieFlags, determineBranch } from 'entities/lib/decode.js';
        ╵                                                               ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "entities/lib/decode.js" as external to exclude it from the bundle, which
  will remove this error.

node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: Build failed with 2 errors:
node_modules/parse5/dist/serializer/index.js:2:44: ERROR: Could not resolve "entities/lib/escape.js"
node_modules/parse5/dist/tokenizer/index.js:4:62: ERROR: Could not resolve "entities/lib/decode.js"
    at failureErrorWithLog (/Users/royrevelt/Documents/__PROJECTS/_____mono/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/royrevelt/Documents/__PROJECTS/_____mono/node_modules/esbuild/lib/main.js:1048:25
    at /Users/royrevelt/Documents/__PROJECTS/_____mono/node_modules/esbuild/lib/main.js:993:52
    at buildResponseToResult (/Users/royrevelt/Documents/__PROJECTS/_____mono/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/royrevelt/Documents/__PROJECTS/_____mono/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/Users/royrevelt/Documents/__PROJECTS/_____mono/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/royrevelt/Documents/__PROJECTS/_____mono/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/royrevelt/Documents/__PROJECTS/_____mono/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 44,
        file: 'node_modules/parse5/dist/serializer/index.js',
        length: 24,
        line: 2,
        lineText: "import { escapeText, escapeAttribute } from 'entities/lib/escape.js';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "entities/lib/escape.js" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "entities/lib/escape.js"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 62,
        file: 'node_modules/parse5/dist/tokenizer/index.js',
        length: 24,
        line: 4,
        lineText: "import { htmlDecodeTree, BinTrieFlags, determineBranch } from 'entities/lib/decode.js';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "entities/lib/decode.js" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "entities/lib/decode.js"'
    }
  ],
  warnings: []
}
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: remark-conventional-commit-changelog-timeline@3.0.7
npm ERR!   at location: /Users/royrevelt/Documents/__PROJECTS/_____mono/packages/remark-conventional-commit-changelog-timeline
npm ERR! Lifecycle script `test` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: remark-conventional-commit-changelog-timeline@3.0.7
npm ERR!   at location: /Users/royrevelt/Documents/__PROJECTS/_____mono/packages/remark-conventional-commit-changelog-timeline
```
